### ISSUE TITLE
Change name of repo to keymanapp/dictionaries

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/lexical-models#49]
Obviously, this incurs MASSIVE changes to e.g., the API, and the CI, but—we've been claiming that users will be installing _dictionaries_ and not _lexical models_. Just like users were able to download and publish keyboards from `keymanapp/keyboards`, they should be able to download and publish dictionaries from `keymanapp/dictionaries`.

@mcdurdin @darcywong00 @jahorton, your comments are very welcome!

**Comment by mcdurdin** [comment]
I want to use the term "lexical model" internally and for developers. For end users, we'll use the term "dictionary". There are many places where we have different end user terminology and in my opinion that is not a big issue. Using the term dictionary internally will shape how people think about the models -- because we are not really publishing dictionaries. So I'm not really keen on this change ;-)

**Comment by mcdurdin** [comment]
FWIW, remember that the end users will not interact directly with the repositories anyway. They'll be finding "dictionaries" installed automatically when they install their keyboard.

**Comment by eddieantonio** [comment]
Fair enough. Given this explanation, I think leaving this repo as `lexical-models` is a good choice. Any comments from other @keymanapp/developers?

**Comment by eddieantonio** [comment]
Alright, calm down you rowdy folk! I'm happy not making an enormous change to our paths and tooling. Closing!
