### ISSUE TITLE
What is the purpose of the .kps file?

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/lexical-models#8]
What purpose does the `.kps` file serve separate from the `.model_info` file? The only think I figure is that the KMP compiler needs it as an argument :/

Can the .kps file be automatically generated? Having to change things in multiple locations (`model.ts`, `.model_info`, `.kps`) is tedious and error prone.

**Comment by mcdurdin** [comment]
We aim for DRY. Sometimes we get a bit damp in places. Remember that `.kmp` files can be created and distributed outside the **lexical-models** repo.

* `.kps` is a package source file. It describes all the files that will be compiled into the `.kmp` archive file, as well as the metadata that is built into `kmp.json` inside the file. A `.kps` file may list more than just the model files; it may list documentation, fonts, required license files, etc.

* `.model_info` is metadata specific to the **lexical-models** repository. It is used to prepare the deployment of the models to the online distribution point, and populate the backend database. Thus it includes some data which is not within a `.kmp` file.

The approach we use is that the `.model_info` can typically be very minimal in the source repository. At compile time, a `build/foo.model_info` is built which merges metadata from the `.kps` file and the `.model_info` file. A minimal `.model_info` will include only the `license` field, which we enforce because we want the model developer to explicitly state this to avoid future issues with copyright, etc.

The [documentation](https://help.keyman.com/developer/cloud/model_info/1.0/) shows which fields are required and how they are populated from other sources during build. There are some optional fields which cannot be generated, e.g. `description`, `related`.

There is a separate challenge around repeating *some* of the metadata in `model.ts` which we haven't 100% covered off yet, I think. I'd be happy to work through any concerns there with you.
